#!/bin/sh

if type brew >/dev/null; then
  # Clean up Homebrew caches.
  brew cleanup -s --prune=7 | /usr/bin/grep -v '^==>' | /usr/bin/grep -v 'Nothing to do' &
  brew cask cleanup | /usr/bin/grep -v '^==>' | /usr/bin/grep -v 'Nothing to do' &
fi

# Clean up Adobe patch files.
/bin/rm -rfv /Applications/Adobe/AdobePatchFiles &
test -d /Applications/Adobe && /bin/rmdir /Applications/Adobe &

# Clean up .DS_Store, desktop.ini and $RECYCLE.BIN in ~/.
/usr/bin/find ~ -d \( -type f -and \( -iname desktop.ini -or -iname .DS_Store \) \) -or \( -type d -iname \$RECYCLE.BIN \) -maxdepth 5 -print0 | xargs -0 /bin/rm -rv &

# Clean up dead symlinks in /Applications.
/usr/bin/find -d -L /Applications -type l -maxdepth 5 -print0 | /usr/bin/xargs -0 /bin/rm -v &

# Clean up dead symlinks in ~/Library.
/usr/bin/find -d -L ~/Library -type l -maxdepth 5 -print0 | /usr/bin/xargs -0 /bin/rm -v &

# Clean up Dropbox conflicts.
dropbox_dir="$(/usr/bin/head -n 2 ~/.dropbox/host.db | /usr/bin/tail -n 1 | /usr/bin/base64 -D)"
if test -d "${dropbox_dir}"; then
  /usr/bin/find -L "${dropbox_dir}" -iname "*in Konflikt stehende*" -maxdepth 20  -print0 | /usr/bin/xargs -0 /bin/rm -v &
fi

wait
